// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	service "git.tmuyu.com.cn/demo/srv/login/pkg/service"
	endpoint "github.com/go-kit/kit/endpoint"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	LoginEndpoint        endpoint.Endpoint
	RefreshTokenEndpoint endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.LoginService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{
		LoginEndpoint:        MakeLoginEndpoint(s),
		RefreshTokenEndpoint: MakeRefreshTokenEndpoint(s),
	}
	for _, m := range mdw["Login"] {
		eps.LoginEndpoint = m(eps.LoginEndpoint)
	}
	for _, m := range mdw["RefreshToken"] {
		eps.RefreshTokenEndpoint = m(eps.RefreshTokenEndpoint)
	}
	return eps
}
