// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	endpoint "git.tmuyu.com.cn/demo/srv/login/pkg/endpoint"
	pb "git.tmuyu.com.cn/demo/srv/login/pkg/grpc/pb"
	grpc "github.com/go-kit/kit/transport/grpc"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	login        grpc.Handler
	refreshToken grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.LoginServer {
	return &grpcServer{
		login:        makeLoginHandler(endpoints, options["Login"]),
		refreshToken: makeRefreshTokenHandler(endpoints, options["RefreshToken"]),
	}
}
